### ISSUE TITLE
traj-parse.py not generating csv file

### ISSUE THREAD

**Issue by asif-nuaa** [jmharkins/trajectory-data#1]
I run "_traj-parse.py_" file but it is not generating csv file for the user. Their is no such code to generate csv file. Can you please provide code for that?

**Comment by jmharkins** [comment]
Hi @asif-nuaa ,

I haven't actually uploaded the data that `traj-parse.py` is supposed to run on. I wrote in the readme of this repo that `traj-parse`: 

> Assumes folder in working directory with unpacked Geolife data as compressed in source link below 

I didn't upload the data as it's quite large and not mine to maintain/upload, but you can find it [here](https://www.microsoft.com/en-us/download/details.aspx?id=52367). If you download it and uncompress and stick it in your own clone of my repo, you should be able to run `traj-parse.py` on your own copy of the GeoLife data, possibly with some modification of line 6 which specifies the directory holding the data:

`data_dir = 'geolife-data/Data'`

Hope that helps

**Comment by asif-nuaa** [comment]
I am able to run traj-parse.py successfully but the code is not generating csv file (e,g it is not generating 010_trip_labeled.csv) that I suppose traj-parse should do.

**Comment by jmharkins** [comment]
Ah sorry - I didn't push the right version which writes the `all_traj` DataFrame object to CSV.

Try again now

**Comment by asif-nuaa** [comment]
Thanks jmharkins. their was the problem in writing to csv file because of join function that you use for dynamic file name generation, but your code solved my purpose as I just gave static file name to write csv by replacing join function.

**Comment by arilwan** [comment]
@asif-nuaa 
having same issue here, how do you fixed it?

**Comment by asif-nuaa** [comment]
> @asif-nuaa
> having same issue here, how do you fixed it?

I found the preprocessed trajectories dataset from google drive repository. that served my purpose. 
https://drive.google.com/drive/u/0/folders/0B_IlYd4BWRmBTXdPSjVGemFpV1E

I used this repository instead
https://github.com/sinadabiri/Transport-Mode-GPS-CNN

**Comment by arilwan** [comment]
Ah, OK.

Many thanks.
